### ISSUE TITLE
Suggestion: mirror whisper.cpp release numbers

### ISSUE THREAD

**Issue by nickv2002** [miyataka/whisper.cpp-docker#5]
eg the tag for the docker image for the [newest release](https://github.com/ggerganov/whisper.cpp/releases/tag/v1.2.1) would be `v1.2.1` rather than [0.9.3](https://github.com/miyataka/whisper.cpp-docker/releases/tag/v0.9.3)

**Comment by miyataka** [comment]
sounds good. I'll do it.

**Comment by miyataka** [comment]
fixed.
https://github.com/miyataka/whisper.cpp-docker/releases/tag/v1.2.1

Thanks! @nickv2002
